
[cursor]
style = { shape = "Beam", blinking = "Off" }

[window]
decorations = "None"
opacity = 0.9
padding = { x = 5, y = 5 }

[font]
normal = { family = "Hack Nerd Font" }
size = 10.0

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/decayce.toml"
  "~/.config/alacritty/rose-pine.toml"
]

